title: 标准化 JavaScript
navigation:
  TC39:
    title: TC39
    agenda: 下一次会议的议程
    notes: 历史会议记录
    sub-menu: 展开 “TC39” 的子列表
  specs:
    title: 规范文件
    proposals: 进行中的提案
    ecma-262: ECMA-262, ECMAScript
    ecma-402: ECMA-402, 国际化 API
    sub-menu: 展开 “规范文件” 的子列表
  contribute:
    title: 贡献
    proposals: 贡献规范正文
    tests: 贡献 test262 测试
    read: 如何阅读规范文件
    discourse: ES Discourse 论坛
    sub-menu: 展开 “贡献” 的子列表
  state-of-proposals: 提案进展概要
  skip-content: 跳转到正文
  open: 打开菜单
footer:
  connect: 联系我们
  contribute: 贡献
  standards: 标准文件
  proposals: 语言提案
  archives: 历史存档
  process: 我们的流程
  coc: Code of Conduct
  feedback: 我们正在寻找反馈
  feedback-prompt: 请通过本链接 <a href="https://github.com/tc39/tc39.github.io/issues/new" target="_blank">提交您的问题</a>。
